"""Add tokens invalid before column to user table

Revision ID: 31fe53421216
Revises: 87a893d57c86
Create Date: 2025-12-29 14:27:16.803188

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31fe53421216"
down_revision: Union[str, Sequence[str], None] = "87a893d57c86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("tokens_invalid_before", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "tokens_invalid_before")
    # ### end Alembic commands ###
