"""Add allowlist table

Revision ID: 87a893d57c86
Revises: 454328a03102
Create Date: 2025-11-13 04:44:28.018622

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "87a893d57c86"
down_revision: Union[str, Sequence[str], None] = "454328a03102"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allowlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("email", "domain", "pattern", name="allowlist_type"),
            nullable=False,
        ),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_allowlist_created_at"), "allowlist", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_allowlist_type"), "allowlist", ["type"], unique=False)
    op.create_index(
        op.f("ix_allowlist_updated_at"), "allowlist", ["updated_at"], unique=False
    )
    op.create_index(op.f("ix_allowlist_value"), "allowlist", ["value"], unique=False)
    op.create_foreign_key(
        None,
        "deployment",
        "user",
        ["created_by_user_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    op.create_foreign_key(
        None,
        "project",
        "user",
        ["created_by_user_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    op.create_foreign_key(
        None,
        "team",
        "user",
        ["created_by_user_id"],
        ["id"],
        ondelete="SET NULL",
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "team", type_="foreignkey")
    op.drop_constraint(None, "project", type_="foreignkey")
    op.drop_constraint(None, "deployment", type_="foreignkey")
    op.drop_index(op.f("ix_allowlist_value"), table_name="allowlist")
    op.drop_index(op.f("ix_allowlist_updated_at"), table_name="allowlist")
    op.drop_index(op.f("ix_allowlist_type"), table_name="allowlist")
    op.drop_index(op.f("ix_allowlist_created_at"), table_name="allowlist")
    op.drop_table("allowlist")
    # ### end Alembic commands ###
