"""Storage

Revision ID: b6bd1dff4015
Revises: 31fe53421216
Create Date: 2026-01-09 02:35:35.553275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6bd1dff4015'
down_revision: Union[str, Sequence[str], None] = '31fe53421216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('database', 'volume', 'kv', 'queue', name='storage_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'deleted', name='storage_status'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('team_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='uq_storage_team_name')
    )
    op.create_index(op.f('ix_storage_created_at'), 'storage', ['created_at'], unique=False)
    op.create_index(op.f('ix_storage_name'), 'storage', ['name'], unique=False)
    op.create_index(op.f('ix_storage_team_id'), 'storage', ['team_id'], unique=False)
    op.create_index('ix_storage_team_name_lower', 'storage', ['team_id', sa.literal_column('lower(name)')], unique=True)
    op.create_index(op.f('ix_storage_updated_at'), 'storage', ['updated_at'], unique=False)
    op.create_table('storage_project',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('storage_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('environment_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('secrets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['storage_id'], ['storage.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_id', 'project_id', name='uq_storage_project')
    )
    op.create_index(op.f('ix_storage_project_project_id'), 'storage_project', ['project_id'], unique=False)
    op.create_index(op.f('ix_storage_project_storage_id'), 'storage_project', ['storage_id'], unique=False)
    op.create_index('ix_project_team_name_lower', 'project', ['team_id', sa.literal_column('lower(name)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_team_name_lower', table_name='project')
    op.drop_index(op.f('ix_storage_project_storage_id'), table_name='storage_project')
    op.drop_index(op.f('ix_storage_project_project_id'), table_name='storage_project')
    op.drop_table('storage_project')
    op.drop_index(op.f('ix_storage_updated_at'), table_name='storage')
    op.drop_index('ix_storage_team_name_lower', table_name='storage')
    op.drop_index(op.f('ix_storage_team_id'), table_name='storage')
    op.drop_index(op.f('ix_storage_name'), table_name='storage')
    op.drop_index(op.f('ix_storage_created_at'), table_name='storage')
    op.drop_table('storage')
    # ### end Alembic commands ###
