"""Add deployment image

Revision ID: d02fb88a3355
Revises: f45484bf96b0
Create Date: 2026-02-01 14:51:05.125947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd02fb88a3355'
down_revision: Union[str, Sequence[str], None] = 'f45484bf96b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployment', sa.Column('image', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployment', 'image')
    # ### end Alembic commands ###
