"""Update deployment

Revision ID: f45484bf96b0
Revises: b6bd1dff4015
Create Date: 2026-01-21 12:48:15.025887

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f45484bf96b0"
down_revision: Union[str, Sequence[str], None] = "b6bd1dff4015"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


new_status_enum = sa.Enum(
    "prepare", "deploy", "finalize", "fail", "completed", name="deployment_status_new"
)

old_status_enum = sa.Enum(
    "queued", "in_progress", "completed", name="deployment_status_old"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployment', sa.Column('error', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'storage', 'user', ['created_by_user_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###

    # Update deployment_status enum to new lifecycle states
    new_status_enum.create(op.get_bind(), checkfirst=True)

    op.execute("ALTER TABLE deployment ALTER COLUMN status DROP DEFAULT")
    op.execute(
        """
        ALTER TABLE deployment
        ALTER COLUMN status TYPE deployment_status_new
        USING (
            CASE status::text
                WHEN 'queued' THEN 'prepare'
                WHEN 'in_progress' THEN 'deploy'
                ELSE status::text
            END
        )::deployment_status_new
        """
    )
    op.execute("DROP TYPE deployment_status")
    op.execute("ALTER TYPE deployment_status_new RENAME TO deployment_status")
    op.execute("ALTER TABLE deployment ALTER COLUMN status SET DEFAULT 'prepare'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'storage', type_='foreignkey')
    op.drop_column('deployment', 'error')
    # ### end Alembic commands ###

    # Recreate old enum and map back
    old_status_enum.create(op.get_bind(), checkfirst=True)
    op.execute("ALTER TABLE deployment ALTER COLUMN status DROP DEFAULT")
    op.execute(
        """
        UPDATE deployment
        SET status = CASE
            WHEN status = 'completed' THEN 'completed'
            WHEN status = 'prepare' THEN 'queued'
            ELSE 'in_progress'
        END
        """
    )
    op.execute(
        "ALTER TABLE deployment ALTER COLUMN status TYPE deployment_status_old USING status::text::deployment_status_old"
    )
    op.execute("DROP TYPE deployment_status")
    op.execute("ALTER TYPE deployment_status_old RENAME TO deployment_status")
    op.execute("ALTER TABLE deployment ALTER COLUMN status SET DEFAULT 'queued'")
